### ISSUE TITLE
Anonymous function in expr() throws exception

### ISSUE THREAD

**Issue by Xenobyte42** [ytsaurus/ytsaurus-spyt#42]
Example to reproduce exception:
```
data = [("James", "Sales", 3000),
("Michael", "Sales", 4600),
("Robert", "Sales", 4100),
("Maria", "Finance", 3000),
("James", "Sales", 3000),
("Scott", "Finance", 3300),
("Jen", "Finance", 3900),
("Jeff", "Marketing", 3000),
("Kumar", "Marketing", 2000),
("Saif", "Sales", 4100)
]

columns = ["employee_name", "department", "salary"]
df = spark.createDataFrame(data, columns)
```

This works fine:
`df.select(f.expr("salary * 2").alias("bonus")).show()`

This isn`t:
`df.select(f.expr("transform(array(salary, 2), x -> x * 2)").alias("bonus")).show()`

This applies to any anonymous functions inside expr

We check same code on version 1.79.0 and it works just fine, on 2.2.0+ it throws exception

Stacktrace:
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.sql.functions.expr.
: java.lang.NoSuchMethodError: 'void org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$1.<init>(org.apache.spark.sql.catalyst.parser.AstBuilderBase)'
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitLambda$1(AstBuilder.scala:1904)
        at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitLambda(AstBuilder.scala:1900)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitLambda(AstBuilder.scala:57)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$LambdaContext.accept(SqlBaseParser.java:15930)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitChildren(AstBuilder.scala:71)
        at org.apache.spark.sql.catalyst.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:1392)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:15298)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.typedVisit(AstBuilder.scala:61)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.expression(AstBuilder.scala:1412)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitPredicated$1(AstBuilder.scala:1548)
        at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitPredicated(AstBuilder.scala:1547)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitPredicated(AstBuilder.scala:57)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:14745)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitChildren(AstBuilder.scala:71)
        at org.apache.spark.sql.catalyst.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:1343)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:14606)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.typedVisit(AstBuilder.scala:61)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.expression(AstBuilder.scala:1412)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitFunctionCall$3(AstBuilder.scala:1835)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitFunctionCall$1(AstBuilder.scala:1835)
        at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitFunctionCall(AstBuilder.scala:1830)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitFunctionCall(AstBuilder.scala:57)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$FunctionCallContext.accept(SqlBaseParser.java:16049)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitChildren(AstBuilder.scala:71)
        at org.apache.spark.sql.catalyst.parser.SqlBaseBaseVisitor.visitValueExpressionDefault(SqlBaseBaseVisitor.java:1392)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$ValueExpressionDefaultContext.accept(SqlBaseParser.java:15298)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.typedVisit(AstBuilder.scala:61)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.expression(AstBuilder.scala:1412)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitPredicated$1(AstBuilder.scala:1548)
        at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitPredicated(AstBuilder.scala:1547)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitPredicated(AstBuilder.scala:57)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$PredicatedContext.accept(SqlBaseParser.java:14745)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitChildren(AstBuilder.scala:71)
        at org.apache.spark.sql.catalyst.parser.SqlBaseBaseVisitor.visitExpression(SqlBaseBaseVisitor.java:1343)
        at org.apache.spark.sql.catalyst.parser.SqlBaseParser$ExpressionContext.accept(SqlBaseParser.java:14606)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.typedVisit(AstBuilder.scala:61)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.expression(AstBuilder.scala:1412)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitNamedExpression$1(AstBuilder.scala:1434)
        at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitNamedExpression(AstBuilder.scala:1433)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.$anonfun$visitSingleExpression$1(AstBuilder.scala:82)
        at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
        at org.apache.spark.sql.catalyst.parser.AstBuilderBase.visitSingleExpression(AstBuilder.scala:82)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.$anonfun$parseExpression$1(ParseDriver.scala:46)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:110)
        at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:51)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseExpression(ParseDriver.scala:45)
        at org.apache.spark.sql.functions$.expr(functions.scala:1482)
        at org.apache.spark.sql.functions.expr(functions.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by alextokarew** [comment]
This is a bug in SPYT 2.2.0, but it is fixed in SPYT 2.3.0
